### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by Tobe2d** [Nuked88/ComfyUI-N-Nodes#47]
Just a question regarding install_extra.bat. 

Is this inteded to be used with comfyui portable, or manual installed using venv?

**Comment by Nuked88** [comment]
Well, If the batch does not find the portable environment then launch the installation in the global environment where the terminal is located.
So if you are in a venv and do not have the portable enviroment then it should still work

**Comment by Tobe2d** [comment]
Thanks for the explanation. I think it is better to use `pip install -r requirements.txt` in my venv
Am I right?

**Comment by Nuked88** [comment]
Actually, it shouldn't be necessary. When you start the node for the first time, it automatically installs all the requirements. The additional batch file only includes 'pip install transformers==4.36.2' since it's necessary for the Moondream model to function. However, if you don't use that model, you can completely skip installing that version of transformers.

**Comment by Tobe2d** [comment]
Awesome, thank you!
